# Thông tin kết nối Supabase
SUPABASE_URL = "https://drglcxvjvtgafxxkuqqn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZ2xjeHZqdnRnYWZ4eGt1cXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDIwNzQsImV4cCI6MjA2MjcxODA3NH0.YUnJROiZlmoH4tKMMeucL1ySHA2XDSqTzXFHynxPAAU
"